service: url-shortener
plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline #serverless-offline needs to be last in the list
provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
          Resource:
            - !GetAtt UrlTable.Arn
            - !GetAtt UrlStatsTable.Arn
  environment:
    STAGE: ${sls:stage}
    URL_TABLE_NAME: !Ref UrlTable
    URL_STATS_TABLE_NAME: !Ref UrlStatsTable
functions:
  handleCreateUrl:
    handler: src/handlers/createUrl.handler
    events:
      - http:
          path: url
          method: post
  handleUrlCreatedEvent:
    handler: src/handlers/urlCreatedEvent.handler
    events:
      - stream:
          type: dynamodb
          arn: !GetAtt UrlTable.StreamArn
          startingPosition: LATEST
          maximumRetryAttempts: 3
          filterPatterns:
            - eventName: [INSERT]
resources:
  Resources:
    UrlTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: url-table
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        StreamSpecification:
          StreamViewType: NEW_IMAGE
    UrlStatsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: url-stats-table
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: originalUrl
            AttributeType: S
        KeySchema:
          - AttributeName: originalUrl
            KeyType: HASH
custom:
  dynamodb:
    stages:
      - dev
    start:
      migrate: true
